### ISSUE TITLE
Typo : CRITIAL VM ERROR

### ISSUE THREAD

**Issue by Aralicia** [Dude112113/Yodine#12]
The error message appearing for some of yolol errors has a typo (see screenshot below).

![image](https://user-images.githubusercontent.com/4456212/79469499-85b7ec00-8000-11ea-9e43-749eeae24baf.png)

**Comment by Avril112113** [comment]
When you get a `CRITIAL VM ERROR` there should also be some info in the console that Yodine opens with, I have added an extra part to the error to say that.
I will fix this now (I already reproduced)
