### ISSUE TITLE
CTD in the Yolol Editor - Backspace madness

### ISSUE THREAD

**Issue by Aralicia** [Dude112113/Yodine#13]
**Steps to Reproduce**
- Place a ChipSocket and put a YololChip in it.
- Open the chip editor
- Type any string
- Press down arrow to move to the second line
- Press up arrow to move back to the first line, but in first position
- Press backspace. **The text on the first line is duplicated.**
- Press backspace again to duplicate the whole line again
- Keep backspace pressed for a few seconds for Yodine to crash

**Comment by Avril112113** [comment]
Steps
- Press down arrow to move to the second line
- Press up arrow to move back to the first line, but in first position

Is not required, only to have the cursor at the begining of the line.
