### ISSUE TITLE
Invalid nan and inf values in fields

### ISSUE THREAD

**Issue by Aralicia** [Dude112113/Yodine#15]
**Description of Issue**
If a statement in Yolol generate a nan (not a number) or inf (infinite value), this value can be placed in a variable or a field.

**Step to reproduce - nan**
Run the following script once :
```
:ChipField1 = ATAN 4
```

**Step to reproduce - inf**
Run the following script for a few seconds :
```
:ChipField1 = 2
:ChipField1 = :ChipField1*:ChipField1 goto 1
```

**Comment by Avril112113** [comment]
Yodine currently does not emulate YOLOL numbers, infact its just Lua numbers at the moment.
I'm not exaclty sure on how to handle NAN and INF at the moment.
