### ISSUE TITLE
Crash on Yolol Execution : invalid goto

### ISSUE THREAD

**Issue by Aralicia** [Dude112113/Yodine#16]
**Description of the issue**
Yodine crashes if goto is given a non-integer numerical value (such as 1.5)
This also occurs if goto is fed a special value (see #15)

**Step to reproduce**
Run the following script :
```
goto 1.5
```

**Comment by Avril112113** [comment]
Partially fixed in commit 25426ca

**Comment by Avril112113** [comment]
I belive the rest of this issue has been resolved by commit 96e2461
