### ISSUE TITLE
Crash when coping and pasting certain things in

### ISSUE THREAD

**Issue by Strikeeaglechase** [Dude112113/Yodine#2]
When pasting in the following code:
```
if :ButtonState then goto 2 end goto 1
:test = 20
:jmp = 2 :from=1 :a=-1// Jump exe to "B" from this chip ("A")
```
The program gives the following error:
```
Error

yolol/parse.lua:28: Invalid op, was unary '/' but expected a valid operator


Traceback

[C]: in function 'error'
yolol/parse.lua:28: in function '_climbPrecedence'
yolol/parse.lua:66: in function '_climbPrecedence'
yolol/parse.lua:75: in function <yolol/parse.lua:73>
[C]: in function 'match'
yolol/parse.lua:312: in function 'parseLine'
devices/chip.lua:114: in function 'codeChanged'
devices/chip.lua:363: in function 'keypressedGUI'
main.lua:301: in function <main.lua:295>
[C]: in function 'xpcall'
```
The issue is repeatable

it appears that the error does not occur when the comment `// Jump exe to "B" from this chip ("A")` is not included

Messing around with the program some more I have found the more general problem.
When you have some valid code followed by the comment it will fail
```[someValidCode] //comment``` <- fails
```
//comment
[someValidCode]                          
//comment
```                                                 <- passes

**Comment by Avril112113** [comment]
Fixed  
The issue was caused by a grammar error  
spesifically `a=1//` the 2nd `/` was being used as an expresion instead of recognising it as a comment
