### ISSUE TITLE
Crash when writing Yolol : double Percent

### ISSUE THREAD

**Issue by Aralicia** [Dude112113/Yodine#6]
**Yolol Code**
`:a%%`

**Crash Dump**
> Error
> 
> yolol/parse.lua:28: Invalid op, was unary '%' but expected a valid operator
> 
> 
> Traceback
> 
> [C]: in function 'error'
> yolol/parse.lua:28: in function '_climbPrecedence'
> yolol/parse.lua:66: in function '_climbPrecedence'
> yolol/parse.lua:75: in function <yolol/parse.lua:73>
> [C]: in function 'match'
> yolol/parse.lua:312: in function 'parseLine'
> devices/YololChip.lua:88: in function 'linesChanged'
> menus/YololChipEditor.lua:32: in function 'linesChanged'
> lfeditor.lua:274: in function 'textinput'
> libs/loveframes/objects/base.lua:257: in function 'textinput'
> libs/loveframes/objects/base.lua:257: in function 'textinput'
> libs/loveframes/init.lua:295: in function 'textinput'
> main.lua:356: in function <main.lua:355>
> [C]: in function 'xpcall'

**Comment by Aralicia** [comment]
This crash probably occurs with any doubled operator. I just got the exact same error writing the following line:
`:LampOn = 1**`

**Comment by Avril112113** [comment]
I have made Yodine not stright up crash on a parse error.
I am still going to fix this though.
